import pandas as pd
import argparse
import sys

if __name__ == "__main__":
    # Initialize argument parser
    parser = argparse.ArgumentParser(description="Summarize the Digitized signal similarity.")
    parser.add_argument("input_csv", help="Path to the input CSV file generated by calc.py")
    args = parser.parse_args()

    # Read input CSV file
    df = pd.read_csv(args.input_csv)
    df["prefix"] = df["path"].str.split("/").str[0]

    # Print summary statistics by dataset
    print("\nSummary Statistics By Dataset:")
    print("================================")
    by_prefix = df[["prefix", "normalized_score"]].groupby("prefix").mean().sort_values("normalized_score")
    print(by_prefix.to_string())
    print("\n" + "=" * 32)

    # Print total average normalized pixel distance score
    total = df["normalized_score"].mean()
    print("\nTotal Digitized Signal Similarity:")
    print("======================================")
    print("Average Score: {:.4f}".format(total))
    print("\n")
